### ISSUE TITLE
ta vacio poh!

### ISSUE THREAD

**Issue by m4ury** [fmoraless/sis_requerimientos#1]
jajjajaja

mira ya subi la version que entregue en github, busca mi usuario
m4ury

**Comment by fmoraless** [comment]
Si. Si en donde hice la instalacion es en asignaciones. El
sis_requerimientos sera el repositorio en comun

**Comment by fmoraless** [comment]
@m4ury  Si. El repositorio sis_requerimientos, está vacío, recien estoy mirando como instalar el Symfony, creo que será la version 2.8, una vez instalado te aviso para que comencemos a meterle codigo, base de datos etc.

**Comment by fmoraless** [comment]
Symfony 2.8 instalado @m4ury Las credenciales de acceso estan compartidas en el documento drive.
[](https://docs.google.com/document/d/1RnhgqiWuEcG4V4Gt8GzvIKeqP4WHa4SOr5KFf5HDIXw/edit)
